{% set name = "libmicrohttpd" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-{{ version }}.tar.gz
  sha256: a89e09fc9b4de34dde19f4fcb4faaa1ce10299b9908db1132bbfa1de47882b94

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libmicrohttpd", max_pin="x.x") }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - gnutls

test:
  commands:
    - test -f $PREFIX/lib/libmicrohttpd${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/microhttpd.h  # [unix]

about:
  home: https://www.gnu.org/software/libmicrohttpd/
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Light HTTP/1.1 server library

extra:
  recipe-maintainers:
    - xhochy
